insert into tipovehiculo (descripcion) values ('Carro')
insert into tipovehiculo (descripcion) values ('Moto')
insert into tiempo (descripcion) values ('Hora')
insert into tiempo (descripcion) values ('Día')
insert into precio (idTipoVehiculo, idTipoTiempo, valor) values ('1','1','1000')
insert into precio (idTipoVehiculo, idTipoTiempo, valor) values ('1','2','8000')
insert into precio (idTipoVehiculo, idTipoTiempo, valor) values ('2','1','500')
insert into precio (idTipoVehiculo, idTipoTiempo, valor) values ('2','2','4000')